### ISSUE TITLE
Usage of @headers during the generation process

### ISSUE THREAD

**Issue by stefano-bragaglia** [antlr4ide/antlr4ide#53]
I have the following configuration in a few projects of mine:
- I move my `Grammar.g4` file into `./src/main/resources`
- I add a `@headers` statement into my `Grammar.g4` like `@header{package my.project.parser;}` so that the parser will be generated into a relative path like `./my/project/parser/`
- I `Enable project specific settings` into the `ANTLR 4` project settings window, specifying `./src/main/java/` as the output directory (`Options` section of the `Tool` subpage) so that the files are generated into `./src/main/java/my/project/parser/`.

Now, it was working perfectly up to the last update of 4 days ago. Today I started a new subproject and I prepared the same project structure as above. It worked for a while and now it doesn't consider anymore the package. Since it was working fine at the beginning, I think it is just a nasty bug... or am I doing something wrong? 

I explicitly passed the whole path as a parameter to the `ANTLR Tool` to work around the problem, but I think it is a bad practice. In this case, in fact, you have to duplicate the `package` information, and it becomes easier for the user to make a mistake.

Just my two cents! Keep up the great work!

**Comment by arifogel** [comment]
Hi I just picked up this project. If this is still an issue, please let me know. If not, I will close as invalid in two weeks.

**Comment by HSorensen** [comment]
I use a slightly different setup to avoid this problem all together since I prefer to separate the generated sources from the non-generated sources.
In the main preferences I specify a relative target:
`./target/generated/antlr-src`

So when I change my grammars in a project the tool will place the generated code relative to that path. 
For the project itself I then define the ./target/generated/antlr-src folder as a source folder.

**Comment by HSorensen** [comment]
Closing this.
